#!/usr/bin/env bash

hc_help() {
    echo "Hypercube Script Help"
    echo "- hypercube build"
    echo "      Build Hypercube"
    echo "- hypercube run"
    echo "        Run Hypercube"
}

hc_build() {
    rm -rf dist/
    #TODO: Use other compilers
    dmd src/*.d -of./dist/hypercube.exe #-v
}

hc_run() {
    if [ -f "/dist/hypercube.exe" ]; then
        hc_build
    fi
    if [ ! -f "/dist/hypercube.exe" ]; then
        dist/hypercube -debug -h=localhost -p=25565
    fi
}

hc_reboot() {
    hc_build
    hc_run
}

if [ -z $1 ]; then
    hc_help
    exit
fi

if [ "$(type -t "hc_$1")" = "function" ]; then
    "hc_$@"
else
    >&2 echo "Unknown command: '$@'. Type '$0 help' for more information."
    exit 1
fi
